In [6]:
import numpy as np

In [11]:
A= np.random.rand(10, 3)

In [13]:
print(A)

[[0.06644749 0.77747092 0.81471861]
 [0.34551214 0.70531791 0.38881375]
 [0.30829854 0.02426456 0.08210699]
 [0.46612216 0.25643253 0.9258948 ]
 [0.34180925 0.72079841 0.84938074]
 [0.18606972 0.68498897 0.07580429]
 [0.14533852 0.37203453 0.23550883]
 [0.2086071  0.30967177 0.27333271]
 [0.06267611 0.32449563 0.72594543]
 [0.62513953 0.95205808 0.18155527]]
